### ISSUE TITLE
Please the windows installation for this doesnt work...tried eveyrthing

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [tgalal/python-axolotl-curve25519#1]
E:\GitHub\yowsup>cd..

E:\GitHub>cd python-axolotl-curve25519

E:\GitHub\python-axolotl-curve25519>python setup.py install
running install
running bdist_egg
running egg_info
writing python_axolotl_curve25519.egg-info\PKG-INFO
writing top-level names to python_axolotl_curve25519.egg-info\top_level.txt
writing dependency_links to python_axolotl_curve25519.egg-info\dependency_links.txt
reading manifest file 'python_axolotl_curve25519.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_axolotl_curve25519.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'axolotl_curve25519' extension
creating build\temp.win-amd64-3.4
creating build\temp.win-amd64-3.4\Release
creating build\temp.win-amd64-3.4\Release\curve
creating build\temp.win-amd64-3.4\Release\curve\ed25519
creating build\temp.win-amd64-3.4\Release\curve\ed25519\additions
creating build\temp.win-amd64-3.4\Release\curve\ed25519\nacl_sha512
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve25519module.c -o build\temp.win-amd64-3.4\Release\curve25519module.o
curve25519module.c: In function 'calculateSignature':
curve25519module.c:50:4: warning: pointer targets in passing argument 1 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
    ^
curve25519module.c:17:5: note: expected 'unsigned char _' but argument is of type 'char *'
 int curve25519_sign(unsigned char_ signature_out,
     ^
curve25519module.c:50:4: warning: pointer targets in passing argument 2 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
    ^
curve25519module.c:17:5: note: expected 'const unsigned char _' but argument is of type 'const char *'
 int curve25519_sign(unsigned char_ signature_out,
     ^
curve25519module.c:50:4: warning: pointer targets in passing argument 3 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
    ^
curve25519module.c:17:5: note: expected 'const unsigned char _' but argument is of type 'const char *'
 int curve25519_sign(unsigned char_ signature_out,
     ^
curve25519module.c:50:4: warning: pointer targets in passing argument 5 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
    ^
curve25519module.c:17:5: note: expected 'const unsigned char _' but argument is of type 'const char *'
 int curve25519_sign(unsigned char_ signature_out,
     ^
curve25519module.c: In function 'verifySignature':
curve25519module.c:76:18: warning: pointer targets in passing argument 1 of 'curve25519_verify' differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                  ^
curve25519module.c:22:5: note: expected 'const unsigned char _' but argument is of type 'const char *'
 int curve25519_verify(const unsigned char_ signature,
     ^
curve25519module.c:76:18: warning: pointer targets in passing argument 2 of 'curve25519_verify' differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                  ^
curve25519module.c:22:5: note: expected 'const unsigned char _' but argument is of type 'const char *'
 int curve25519_verify(const unsigned char_ signature,
     ^
curve25519module.c:76:18: warning: pointer targets in passing argument 3 of 'curve25519_verify' differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                  ^
curve25519module.c:22:5: note: expected 'const unsigned char _' but argument is of type 'const char *'
 int curve25519_verify(const unsigned char_ signature,
     ^
curve25519module.c: At top level:
curve25519module.c:159:9: warning: initialization makes integer from pointer without a cast
         NULL,
         ^
curve25519module.c:159:9: warning: (near initialization for 'curve25519_module.m_size')
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/curve25519-donna.c -o build\temp.win-amd64-3.4\Release\curve\curve25519-donna.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_0.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_0.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_1.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_1.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_add.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_add.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_cmov.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_cmov.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_copy.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_copy.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_frombytes.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_frombytes.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_invert.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_invert.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_isnegative.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_isnegative.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_isnonzero.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_isnonzero.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_mul.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_mul.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_neg.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_neg.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_pow22523.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_pow22523.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_sq.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_sq.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_sq2.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_sq2.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_sub.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_sub.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\fe_tobytes.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_tobytes.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_add.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_add.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_double_scalarmult.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_double_scalarmult.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_frombytes.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_frombytes.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_madd.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_madd.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_msub.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_msub.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p1p1_to_p2.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p1p1_to_p2.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p1p1_to_p3.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p1p1_to_p3.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p2_0.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p2_0.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p2_dbl.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p2_dbl.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p3_0.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_0.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p3_dbl.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_dbl.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p3_tobytes.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_tobytes.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p3_to_cached.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_to_cached.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_p3_to_p2.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_to_p2.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_precomp_0.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_precomp_0.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_scalarmult_base.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_scalarmult_base.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_sub.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_sub.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\ge_tobytes.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_tobytes.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\open.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\open.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\sc_muladd.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\sc_muladd.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\sc_reduce.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\sc_reduce.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519\sign.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\sign.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519/additions\compare.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\compare.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519/additions\curve_sigs.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\curve_sigs.o
curve/ed25519/additions\curve_sigs.c: In function 'curve25519_keygen':
curve/ed25519/additions\curve_sigs.c:10:6: warning: unused variable 'ed_y' [-Wunused-variable]
   fe ed_y, ed_y_plus_one, one_minus_ed_y, inv_one_minus_ed_y;
      ^
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519/additions\sign_modified.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\sign_modified.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519/additions\zeroize.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\zeroize.o
curve/ed25519/additions\zeroize.c: In function 'zeroize':
curve/ed25519/additions\zeroize.c:6:17: warning: unused variable 'retval' [-Wunused-variable]
   unsigned long retval = 0;
                 ^
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519/nacl_sha512\blocks.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\nacl_sha512\blocks.o
c:\mingw\bin\gcc.exe -mdll -O -Wall -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 "-IC:\Program Files\Python34\include" "-IC:\Program Files\Python34\include" -c curve/ed25519/nacl_sha512\hash.c -o build\temp.win-amd64-3.4\Release\curve\ed25519\nacl_sha512\hash.o
writing build\temp.win-amd64-3.4\Release\axolotl_curve25519.def
creating build\lib.win-amd64-3.4
c:\mingw\bin\gcc.exe -shared -s build\temp.win-amd64-3.4\Release\curve25519module.o build\temp.win-amd64-3.4\Release\curve\curve25519-donna.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_0.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_1.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_add.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_cmov.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_copy.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_frombytes.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_invert.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_isnegative.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_isnonzero.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_mul.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_neg.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_pow22523.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_sq.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_sq2.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_
sub.o build\temp.win-amd64-3.4\Release\curve\ed25519\fe_tobytes.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_add.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_double_scalarmult.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_frombytes.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_madd.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_msub.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p1p1_to_p2.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p1p1_to_p3.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p2_0.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p2_dbl.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_0.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_dbl.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_tobytes.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_to_cached.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_p3_to_p2.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_precomp_0.o build\temp.win-amd64-3.
4\Release\curve\ed25519\ge_scalarmult_base.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_sub.o build\temp.win-amd64-3.4\Release\curve\ed25519\ge_tobytes.o build\temp.win-amd64-3.4\Release\curve\ed25519\open.o build\temp.win-amd64-3.4\Release\curve\ed25519\sc_muladd.o build\temp.win-amd64-3.4\Release\curve\ed25519\sc_reduce.o build\temp.win-amd64-3.4\Release\curve\ed25519\sign.o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\compare.o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\curve_sigs.o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\sign_modified.o build\temp.win-amd64-3.4\Release\curve\ed25519\additions\zeroize.o build\temp.win-amd64-3.4\Release\curve\ed25519\nacl_sha512\blocks.o build\temp.win-amd64-3.4\Release\curve\ed25519\nacl_sha512\hash.o build\temp.win-amd64-3.4\Release\axolotl_curve25519.def "-LC:\Program Files\Python34\libs" "-LC:\Program Files\Python34\PCbuild\amd64" -lpython34 -lmsvcr100 -o build\lib.win-amd64-3.4\axolotl_curve25519
.pyd
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x48): undefined reference to `__imp_PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x6d): undefined reference to`__imp_PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x110): undefined reference to `__imp_PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x189): undefined reference to`__imp_PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x229): undefined reference to `__imp_PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x24e): more undefined references to`__imp_PyExc_ValueError' follow
collect2.exe: error: ld returned 1 exit status
error: command 'c:\mingw\bin\gcc.exe' failed with exit status 1

E:\GitHub\python-axolotl-curve25519>

**Comment by CharlesOkwuagwu** [comment]
dependency install fails too

**Comment by CharlesOkwuagwu** [comment]
E:\GitHub\python-axolotl-curve25519>Install zlib
Install: missing destination file operand after `zlib'
Try`Install --help' for more information.

E:\GitHub\python-axolotl-curve25519>python Install zlib
python: can't open file 'Install': [Errno 2] No such file or directory

E:\GitHub\python-axolotl-curve25519>python -m PIP Install zlib
C:\Program Files\Python34\python.exe: No module named PIP

E:\GitHub\python-axolotl-curve25519>easy_install zlib
Searching for zlib
Reading https://pypi.python.org/simple/zlib/
Couldn't find index page for 'zlib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
C:\Program Files\Python34\lib\site-packages\setuptools-11.3.1-py3.4.egg\pkg_resources__init__.py:2510: PEP440Warning: 'getpaid.recipe.release (fix)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
No local packages or download links found for zlib
error: Could not find suitable distribution for Requirement.parse('zlib')

E:\GitHub\python-axolotl-curve25519>

**Comment by aesedepece** [comment]
@CharlesOkwuagwu How did you solve this?

**Comment by CharlesOkwuagwu** [comment]
@aesedepece
i dropped this python lib. 
Re-wrote mine from scratch with .Net

**Comment by natanfrost** [comment]
Can you provide your re-wroted solution?
