### ISSUE TITLE
Bitwise operations on secret key

### ISSUE THREAD

**Issue by gjedeer** [tgalal/python-axolotl-curve25519#11]
I'm wondering what's the reason why there are bit-wise operations on the secret key in generatePrivateKey():

https://github.com/tgalal/python-axolotl-curve25519/blame/e4a9c4de0eae27223200579c58d1f8f6d20637e2/curve25519module.c#L98

I've been trying to find something similar in the reference 25519 [implementation by Bernstein](https://ed25519.cr.yp.to/python/ed25519.py) and I could not. Care to point me in the right direction?

**Comment by Vinc0682** [comment]
These operations are specified on Bernstein's official homepage: https://cr.yp.to/ecdh.html

**Comment by gjedeer** [comment]
I see, he just used a precomputed secret key that's why these operations were already performed. Thanks @Vinc0682
