### ISSUE TITLE
Where can i find a test script?

### ISSUE THREAD

**Issue by Tungsteno74** [tgalal/python-axolotl-curve25519#12]
Hello tgalal,

these days I've been able to compile this package for **python 2.7.x on windows 64bit** by modify the curve25519module.c file (this should fix #5 issue). I did this change with no errors, only a warning. 
Now I want to be sure that the edit file works well before share this update.

Since I do not know what features/functions are implemented in this package, could you provide me a small script (something like a 'unittest') that use all working functions and some checking output?

Thanks again for your great work

**Comment by tgalal** [comment]
See [python-axolotl](https://github.com/tgalal/python-axolotl)
