### ISSUE TITLE
Installation issue after update

### ISSUE THREAD

**Issue by PyWaves** [tgalal/python-axolotl-curve25519#19]
Hi Tarek,

thanks for accepting the pull request fixing the limit of the message length. Anyway, when i now try to install the library via pip, i get the following error:

The directory '/Users/marcjansen/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/marcjansen/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-axolotl-curve25519
  Downloading python-axolotl-curve25519-0.4.1.post1.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 1.3MB/s 
Installing collected packages: python-axolotl-curve25519
  Running setup.py install for python-axolotl-curve25519 ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-VWQUs5/python-axolotl-curve25519/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u9E4Pi-record/install-record.txt --single-version-externally-managed --compile:
    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py:285: UserWarning: Normalizing '0.4.1-1' to '0.4.1.post1'
      normalized_version,
    running install
    running build
    running build_ext
    building 'axolotl_curve25519' extension
    error: unknown file type '.h' (from 'curve/ed25519/additions/compare.h')
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-VWQUs5/python-axolotl-curve25519/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u9E4Pi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-VWQUs5/python-axolotl-curve25519/

Greets
  Marc

**Comment by tgalal** [comment]
sorry I screwed up the release, fixed in 0.4.1-2

**Comment by PyWaves** [comment]
Works perfect now! Thanks a lot!

2018-04-14 12:48 GMT+02:00 Tarek <notifications@github.com>:

**Comment by SalahAdDin** [comment]
@tgalal I'm still getting this bug:
```
Running setup.py install for python-axolotl-curve25519: started
    Running setup.py install for python-axolotl-curve25519: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-16iqgzg4/python-axolotl-curve25519/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zza5yxr7-record/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python3.5/dist-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.4.1-2' to '0.4.1.post2'
      normalized_version,
    running install
    running build
    running build_ext
    building 'axolotl_curve25519' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/curve
    creating build/temp.linux-x86_64-3.5/curve/ed25519
    creating build/temp.linux-x86_64-3.5/curve/ed25519/additions
    creating build/temp.linux-x86_64-3.5/curve/ed25519/nacl_sha512
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Icurve/ed25519/nacl_includes -Icurve/ed25519/additions -Icurve/ed25519 -I/usr/include/python3.5m -c curve/curve25519-donna.c -o build/temp.linux-x86_64-3.5/curve/curve25519-donna.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-16iqgzg4/python-axolotl-curve25519/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zza5yxr7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-16iqgzg4/python-axolotl-curve25519/
```

**Comment by jsam2412** [comment]
@SalahAdDin have you found the solution?
I am also gettig the same error

**Comment by SalahAdDin** [comment]
No, i left it long time ago.

**Comment by arturspon** [comment]
I got it after running this:
`sudo apt-get install cmake`
`sudo apt-get install gcc g++`
`sudo apt-get install python3-dev python3-numpy`
